server:
  port: 9191

spring:
  application:
    name: TRADING-GATEWAY
  cloud:
    config:
      profile: local
      name: gateway,eureka-client
  config:
    import:
      - optional:configserver:https://setlog.net/trading-config-server/